export const GET_DEVICE_TYPE_AIR = 'GET_DEVICE_TYPE_AIR';
export const GET_DEVICE_DETAIL = 'GET_DEVICE_DETAIL';
export const GET_DEVICE_ID_IN_WEEK = 'GET_DEVICE_ID_IN_WEEK';
export const LOADING = 'LOADING';
export const GET_DEVICE_TYPE_LIGHT = 'GET_DEVICE_TYPE_LIGHT';
export const GET_DEVICE_TYPE_MOTOR = 'GET_DEVICE_TYPE_MOTOR';
